# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-18 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue_log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField(max_length=200)),
                ('is_priority', models.BooleanField()),
                ('issued_on', models.DateTimeField(auto_now_add=True)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue_log.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_index', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='severity_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue_log.Severity'),
        ),
    ]
