# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-18 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_log', '0003_auto_20160718_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='is_priority',
            field=models.NullBooleanField(),
        ),
    ]
